### PR TITLE
Add standards for installing and upgrading Magento extensions

### PR DESCRIPTION
**Pull request by tgerulaitis**

### CODE REVIEW

**Comment by bobbyshaw** [comment]
Looks good!

**Comment by punkstar** [comment]
I've merged this, but I've received an email from Github with the following:

> The page build failed with the following error:
> 
> Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.
> 
> If you have any questions you can contact us by replying to this email.

**Comment by tgerulaitis** [comment]
There's really nothing I can do with that information. I haven't added any new plugins, I very much doubt my changes increased the repo size to over 1GB and the push was made by @punkstar, who I assume has a verified email address and has setup a deploy key, as this is not the first deployment. In addition, the site builds fine on Travis and locally.

**Comment by punkstar** [comment]
Forcing a rebuild with `git commit -m 'Force rebuild of github pages' --allow-empty` fixed the issue.  Sigh.

**Pull request merged**
